# Helm job that migrates database
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tva.fullname" . }}
  labels:
    {{- include "tva.labels" . | nindent 4 }}
  annotations:
    # If stated as pre-install, the job does not run due to the db not existing
    # However, we will want to run this pre-upgrade (as the db does exist)
    "helm.sh/hook": pre-upgrade, post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "tva.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: "{{ .Chart.Name }}-db-migrator-job"
        image: "ghcr.io/jhnoor/multi-cluster-of-madness/tva-db-migrator:latest"
        env:
          - name: ConnectionStrings__DefaultConnection
            value: Server={{ .Release.Name }}-postgresql;Port={{ .Values.postgresql.servicePort }};Database={{ .Values.postgresql.postgresqlDatabase }};User Id={{ .Values.postgresql.postgresqlUsername }};Password={{ .Values.postgresql.postgresqlPassword }}
        command: ["/bin/bash", "-c", "/app/efbundle"]
