apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: spider-men
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-01-30T09:39:16Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: spider-men
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spider-men
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: spider-men-0.0.1
  name: spider-men
  namespace: default
  resourceVersion: "949"
  uid: 7d04b3e5-5aa4-4e6e-9435-70cc5e3465cd
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: spider-men
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
